apiVersion: v1
kind: Service

# Name of service
metadata:
  name: order-ms

# load balancer type for ELB external access
spec:
  type: LoadBalancer

  # pods with order-ms label
  selector:
    app: order-ms
  ports:
    - port: 8081
      targetPort: 8081